kind: Deployment
metadata:
  name: event-service
  labels:
    app: event-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: event-service
  template:
    metadata:
      labels:
        app: event-service
    spec:
      containers:
      - name: event-service
        image: event-service:latest      # sera remplacé par Kustomize/ECR URI
        ports:
        - containerPort: 8080
